### ISSUE TITLE
TypeScript types not present in npm package

### ISSUE THREAD

**Issue by edhedges** [ethereumjs/ethereumjs-wallet#103]
The title basically says it all, but I noticed that the source for the repo is written in TypeScript, but when using `npm i ethereumjs-wallet --save` and running `ls node_modules/ethereumjs-wallet`, I'm not seeing a `dist` directory, nor am I seeing any `*.ts` or `*.d.ts` files.

**Comment by holgerd77** [comment]
TypeScript version of the library has not been released yet, the docs PR https://github.com/ethereumjs/ethereumjs-wallet/pull/98 review is still pending. Not a great thing but we've a bit lost track on this, will keep up soon, review and then release.

If you have a look over the PR feel also free to directly make some comments, this will ease a subsequent review and likely accelerate stuff.
