### ISSUE TITLE
Question: New release date?

### ISSUE THREAD

**Issue by zcstarr** [ethereumjs/ethereumjs-wallet#104]
Hi all, this project looks awesome, is there an eta on doing another release, I'd like to be able to refer to the typescript based release. Otherwise I'll probably end up forking it and releasing off of the fork.  Thanks!

**Comment by holgerd77** [comment]
Will close in favor of https://github.com/ethereumjs/ethereumjs-wallet/pull/120

Note: `TypeScript` release is now really one days or maximally 1-2 weeks away.
