### ISSUE TITLE
Could not import ethereumjs-wallet into my TypeScript project

### ISSUE THREAD

**Issue by chiro-hiro** [ethereumjs/ethereumjs-wallet#105]
I've found this error:
```
Could not find a declaration file for module 'ethereumjs-wallet'. '/home/chiro/gits/blockchain/node_modules/ethereumjs-wallet/index.js' implicitly has an 'any' type.
  Try `npm install @types/ethereumjs-wallet` if it exists or add a new declaration (.d.ts) file containing `declare module 'ethereumjs-wallet';`
````
I realized there are no `.d.ts` files in the package. I'm proposing to have these file in package.

**Comment by holgerd77** [comment]
The `TypeScript` version of the library in the `master` branch is not released yet, this will happen sometime in January 2020, then issues like this one will be resolved.
