### ISSUE TITLE
getAddress() fails in Firefox

### ISSUE THREAD

**Issue by d10r** [ethereumjs/ethereumjs-wallet#11]
Code:
```
import Wallet from 'ethereumjs-wallet'
export class Test {
    constructor() {
        this.wallet = Wallet.generate()
        let addr = this.wallet.getAddress()
        console.log(JSON.stringify(addr))
    }
}
```

Error in browser console:
```
Message: false == true
Inner Error Stack:
exports.publicToAddress@http://localhost:9000/jspm_packages/npm/ethereumjs-util@4.5.0/index.js:148:5
Wallet.prototype.getAddress@http://localhost:9000/jspm_packages/npm/ethereumjs-wallet@0.6.0/index.js:64:12
Test@http://localhost:9000/dist/test.js:22:28
```

It's this line:
```assert(pubKey.length === 64);```
here: https://github.com/ethereumjs/ethereumjs-util/blob/v4.5.0/index.js#L342

I stepped through it once in debugger. pubKey.length is 65.

Tested on Firefox 49.0.2 and 51.0a2 (dev) on Linux 64bit.
On current Chromium it works fine.

I'm not sure if the issue is in ethereumjs-wallet or in ethereumjs-util (or even a in dependency below).

**Comment by d10r** [comment]
Update:
After manually building a bundle with browserify, it works in Firefox too.
The issue described happened in an Aurelia project using jspm for package management.

**Comment by holgerd77** [comment]
Too specific issue being too old to recreate, will close.
