### ISSUE TITLE
Remove ProviderEngine

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-wallet#115]
Support for ProviderEngine implemented in [provider-engine.ts](https://github.com/ethereumjs/ethereumjs-wallet/blob/master/src/provider-engine.ts) is bringing in the [web3-provider-engine](https://github.com/MetaMask/web3-provider-engine) dependency.

This draws in a [myriad of unnecessary additional dependencies](https://github.com/MetaMask/web3-provider-engine/blob/master/package.json) which are often outdated since the package is not very actively maintained and [superseded by `json-rpc-engine`](https://github.com/MetaMask/web3-provider-engine#web3-providerengine). This is problematic from a security POV (mildly speaking) and significantly diminishes the installation experience especially through various older versions of the hashing libraries (`keccak`, `secp2561`) drawn in.

I would suggest to remove this feature, it should be relatively easily possible to do this integration on the user side if needed by adopting the code from [provider-engine.ts](https://github.com/ethereumjs/ethereumjs-wallet/blob/master/src/provider-engine.ts).

//cc @kumavis

**Comment by kumavis** [comment]
@holgerd77 find by me :+1: , be sure to respect semver in its removal
