### ISSUE TITLE
toV3() takes a lot of time to process

### ISSUE THREAD

**Issue by or2008** [ethereumjs/ethereumjs-wallet#12]
it takes about 10 seconds to run this function, is it a bug?

if not, is there a way to run it asynchronously?

**Comment by axic** [comment]
It is by design. The V3 keystore format uses scrypt, which is CPU heavy.

etheruemjs-wallet only provides the raw methods to interact with keys and keystore formats. If you are using a browser, I suggest looking into *workers* and offloading this process to a worker.

**Comment by or2008** [comment]
yes I am running it in the browser, I'll check the web workers options.

Thank you!
