### ISSUE TITLE
Broken CI runner with upgrade to 0.6.5

### ISSUE THREAD

**Issue by junderw** [ethereumjs/ethereumjs-wallet#132]
We recently started updating an internal library that depends on `^0.6.3` of this library, and our CI was throwing segfaults.

I tried changing it to `0.6.4` and it worked, then `0.6.5` threw the same segfault at the same part. (It's our internal test for a signing helper function for transactions)

I have temporarily fixed this issue by changing from `^0.6.3` to a specific version, but just thought I'd let you know about this issue. Reverting the change and publishing a 0.6.6 version would be appreciated. (This change should be put off until a major version bump)

Thank you.

**Comment by junderw** [comment]
(I am referring to #130 )

**Comment by alcuadrado** [comment]
Hi @junderw. Thanks for reporting this.

Do you have a link to your ci failure? If not, can you provide more info about the environment it's running on and what the test is doing?

Thanks

**Comment by junderw** [comment]
Sorry... it is a private repository, so no link.

Additional info we found: it was only crashing on `node:12.13.0-alpine` but not `node:12.13.0`...

So perhaps the code used in 0.6.5 is relying on glibc? (googling the issue, it seems like random segfaults on alpine are usually caused by glibc not being there)

**Comment by alcuadrado** [comment]
> So perhaps the code used in 0.6.5 is relying on glibc?

Yes, that's also my suspicion. This was present un `keccak` and `secp256k1` until a few days ago.

Can you confirm that you were using the latest versions of these libraries? Maybe you had an older `package-lock.json`/`yarn.lock`.

For more info:
* https://github.com/cryptocoinjs/keccak/pull/16
* https://github.com/cryptocoinjs/secp256k1-node/pull/169

**Comment by holgerd77** [comment]
@junderw any update on this?

**Comment by junderw** [comment]
I'll go ahead and close this... it was probably a lockfile keeping a dependency from updating... but the funny thing was that it was working fine up until I updated a dependency that depended on this library...

Perhaps another dependency had one of those deps and the highest common version requirement between this library and the other library was a version with the issue not fixed yet...

Either way, we decided to switch to debian based image instead of alpine.
