### ISSUE TITLE
fromV3 broken in 0.6.3+

### ISSUE THREAD

**Issue by Cr0wn-Gh0ul** [ethereumjs/ethereumjs-wallet#137]
```
Wallet.fromV3(keystore, password)
```
in versions < 0.6.3 work fine, but in version 1.0.0 it results in a thrown error: `"list" argument must be an Array of Buffers`

**Comment by chaitanyapotti** [comment]
PR #135  fixes this. I hope they merge it soon

**Comment by kumavis** [comment]
resolved in #135
