### ISSUE TITLE
Missing API method to validate a publicKey, privateKey pair

### ISSUE THREAD

**Issue by wparad** [ethereumjs/ethereumjs-wallet#142]
It would be awesome to have a method on the `Wallet` `.verifyPublicKey(publicKey)`.

**Comment by holgerd77** [comment]
@wparad thanks for the suggestion, should be easily doable with functionality used [here](https://github.com/ethereumjs/ethereumjs-wallet/blob/13fb20d/src/index.ts#L472), will add some respective labels to the issue.
