### ISSUE TITLE
Wallet is not exported for typescript.

### ISSUE THREAD

**Issue by emilakesson99** [ethereumjs/ethereumjs-wallet#152]

**Comment by holgerd77** [comment]
Lacking context, will close.

**Comment by emilakesson99** [comment]
Solved it. You should remove the brackets for the typescript import documentation 👍

**Comment by holgerd77** [comment]
Thanks, could you point us to the code? Still not sure what you mean...

**Comment by emilakesson99** [comment]
At [this ](https://github.com/ethereumjs/ethereumjs-wallet)page and scroll down to :

import { Wallet } from 'ethereumjs-wallet'

For me, it had to be like this:

import Wallet from 'ethereumjs-wallet'

A very minor doc mistake, I guess. 

I'm running typescript in nodejs though. So don't know the semantics there.  Sorry for being abrupt.

**Comment by holgerd77** [comment]
@emilakesson99 ah, thanks a lot for pointing out, have updated. 😄
