### ISSUE TITLE
Wallet generated keys is not accepted by the Utils library.

### ISSUE THREAD

**Issue by emilakesson99** [ethereumjs/ethereumjs-wallet#153]
When I run my wallet generated keys through Ethereumjs-utils library functions, isValidpublic and isValidPrivate it returns false on the public one. 

For the private, I get this error: 

"Expected private key to be an Uint8Array with length 32"

Are the libraries not compatible?

Code:
`let publicKey: Buffer = wallet.getPrivateKey()
      let privateKey: Buffer = wallet.getPublicKey()
      if (!isValidPublic(publicKey)) {
        console.log('public key is not vaild')
      }
      if (!isValidPrivate(privateKey)) {
        console.log('private key is not vaild')
      }`

**Comment by Devmenai** [comment]
> When I run my wallet generated keys through Ethereumjs-utils library functions, isValidpublic and isValidPrivate it returns false on the public one. 
> 
> For the private, I get this error: 
> 
> "Expected private key to be an Uint8Array with length 32"
> 
> Are the libraries not compatible?
> 
> Code:
> `let publicKey: Buffer = wallet.getPrivateKey()
>       let privateKey: Buffer = wallet.getPublicKey()
>       if (!isValidPublic(publicKey)) {
>         console.log('public key is not vaild')
>       }
>       if (!isValidPrivate(privateKey)) {
>         console.log('private key is not vaild')
>       }`


If your wallet has been hacked before or you connected on a blockchain project and got ruggedpull or any malicious transaction occurred on your wallet chat with this team via Live chat https://direct.lc.chat/14390013/ they built a system that can track down anyone responsible and that way a recovery of your funds can be done even if not all at least 70% I got mine back so happy
