### ISSUE TITLE
TypeError: this._hdkey.derive is not a function

### ISSUE THREAD

**Issue by ekkis** [ethereumjs/ethereumjs-wallet#175]
when I run:
```js
const Wallet = require('ethereumjs-wallet');
const EthUtil = require('ethereumjs-util')

const pk = '0xb38X1f01XXXf3f15fXXb20XX480ec1fb93d62XXXb6641390fXXXXXXXXXX693XX'

const h = new Wallet.hdkey(pk)
const mn = h.derivePath("m/44'/60'/0'")
```
I get:

> /Users/ekkis/dev/eth/node_modules/ethereumjs-wallet/dist/hdkey.js:46
>         return new EthereumHDKey(this._hdkey.derive(path));
>                                              ^
> 
> TypeError: this._hdkey.derive is not a function
>     at EthereumHDKey.derivePath (/Users/ekkis/dev/eth/node_modules/ethereumjs-wallet/dist/hdkey.js:46:46)
>     at Object.<anonymous> (/Users/ekkis/dev/eth/bip32-to-xpub.js:21:14)
>     at Module._compile (node:internal/modules/cjs/loader:1119:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
>     at Module.load (node:internal/modules/cjs/loader:997:32)
>     at Module._load (node:internal/modules/cjs/loader:838:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
>     at node:internal/main/run_main_module:18:47
> 
> Node.js v18.8.0

this is with "ethereumjs-wallet": "^1.0.2".  what am I missing?

**Comment by holgerd77** [comment]
Sorry, we don't have really good and complete initialization and usage examples on the [README](https://github.com/ethereumjs/ethereumjs-wallet) I just realize. So your initialization is wrong - `new Wallet` just doesn't work - have a look at the main [test file](https://github.com/ethereumjs/ethereumjs-wallet/blob/master/test/index.spec.ts) for some inspiration on how to initialize a `Wallet`.

Will close here for now, feel free to reopen if issues still persist.
