### ISSUE TITLE
different ETH keys for the same mnemonic

### ISSUE THREAD

**Issue by hasq123** [ethereumjs/ethereumjs-wallet#178]
Hi everyone.
I use golang library for creating HD wallets: 

```golang
import (
	"fmt"
	"log"

	"github.com/lizc2003/hdwallet/wallet"
)

mnemonic := "thumb...."
w, err = hdw.NewWallet(wallet.SymbolEth, 0, 0, 0)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wallet: %s\n\tprivatekey: %s\n\tpublickey: %s\n\taddress: %s\n",
		w.Symbol(),
		w.DerivePrivateKey(),
		w.DerivePublicKey(),
		w.DeriveAddress())	

```

as derived address I got: `address: 0x05D29c8C..................8DAb2ff43e2e3C310`

I want to move my solution to ethereumjs, and I use the same mnemonic

```js
const {hdkey} = require("ethereumjs-wallet")

let mnemonic = "thumb...."

let buffer = Buffer.from(mnemonic)
let hd_priv_key = hdkey.fromMasterSeed(buffer)
let address = hd_priv_key.deriveChild(0).getWallet().getAddressString()

console.log(address)
```

and I got `0xd5b8f015............8a481933ba2a8336`

what is the difference, 

note: the same address as for golang I got on https://iancoleman.io/bip39/

could you explain and help with it?

**Comment by kaliubuntu0206** [comment]
Your code is wrong btw.

You should convert the mnemonics to entropy ( or so called seeds ) according to the BIP39 specification.

See https://github.com/kaliubuntu0206/ethereumjs-wallet/blob/master/test/hdkey.spec.ts#L30 for how I accomplished it though.
