### ISSUE TITLE
Packages.json needs to contain all the used packages

### ISSUE THREAD

**Issue by omardiaa** [ethereumjs/ethereumjs-wallet#179]
The following packages were not installed when I tried to install `ethereumjs-wallet` into my project:
- `stream`
- `assert`
- `buffer`
-  `crypto`

Suggested change:
Add the following to packages.json inside dependencies:
"dependencies": {
     "assert": "^2.0.0",
    "buffer": "^6.0.3",
    "crypto": "^1.0.1",
    "stream": "^0.0.2"
  }

**Comment by acolytec3** [comment]
Are you using this in browser?  Those look like polyfills for NodeJS builtin modules used by this library and we wouldn't include those in our `package.json` since this library doesn't currently provide a browser-specific build (though not to say we can't explore that).
