### ISSUE TITLE
Import from private key not working

### ISSUE THREAD

**Issue by rhlsthrm** [ethereumjs/ethereumjs-wallet#20]
I exported my JSON wallet account from Parity and decrypted the JSON file in MyEtherWallet.

When I tried to use `.fromV3(Buffer.from('<PRIVATE_KEY>')`, I get an error:

`Error: Private key does not satisfy the curve requirements (ie. it is invalid)`

I am not sure why this would not work, the private key should definitely be valid.

**Comment by fanatid** [comment]
How private key looks like? If it was hex, should be: `Buffer.from('<PRIVATE_KEY>', 'hex')`

**Comment by rhlsthrm** [comment]
Thank you!
