### ISSUE TITLE
Create tests to achieve 100% coverage

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-wallet#26]
A couple of simple tests can be added to cover `index.js` (except the `fromV1` function). Covering `thirdparty.js` is secondary.

**Comment by holgerd77** [comment]
Not sure if I find some time but if so would it be ok to directly push some additional tests to the dependency-update PR https://github.com/ethereumjs/ethereumjs-wallet/pull/25?

**Comment by axic** [comment]
I'd create a new PR off that. Want to merge #25 once ethereumjs-util 5.1.4 is released.

**Comment by stvtortora** [comment]
Hey, do you still need help with this issue? I'd bee happy to take it.

**Comment by alcuadrado** [comment]
Hey @stvtortora! Help on this would be great!

[According to coveralls](https://coveralls.io/github/ethereumjs/ethereumjs-wallet), the third party module is the least tested. It contains utility functions to encode/decode wallets generated by different apps. 

Let me know if you need help with this.

**Comment by holgerd77** [comment]
Hi @stvtortora that's nice, thanks for the offer! 😄 Please be aware of this open PR https://github.com/ethereumjs/ethereumjs-wallet/pull/86 from @chikeichan. We forgot a bit about that unfortunately, but would be nice if we would get this updated and merged along.
