### ISSUE TITLE
generate() doesn't return unique public address always.

### ISSUE THREAD

**Issue by StarNeit** [ethereumjs/ethereumjs-wallet#29]
Hi.

generate() doesn't return unique public address always.

I have seen that generate() returns same public address sometimes.

Is that critical issue of this wallet?

**Comment by axic** [comment]
`generate()` depends on the underlying `crypto.randomBytes`, which may have different level of randomness on different browsers / platforms. Perhaps the setup you are using doesn't provide sufficient randomness.

What is you setup?

**Comment by axic** [comment]
Please reopen if it still persists by using a proper underlying `randomBytes` method.
