### ISSUE TITLE
can't npm install on mac

### ISSUE THREAD

**Issue by or2008** [ethereumjs/ethereumjs-wallet#32]
Hi,
I tried to run `npm i ethereumjs-wallet` on my mac, but it failed with this error:

![image](https://user-images.githubusercontent.com/3414979/36561483-780f6234-181c-11e8-984f-d34fcbf4cee0.png)

**Comment by fanatid** [comment]
Issue related with https://github.com/barrysteyn/node-scrypt not with `ethereumjs-wallet`.

**Comment by holgerd77** [comment]
I also just live-tested this on a mac and it works. You probably have to google your way through the other error messages, e.g. the one from XCode.
