### ISSUE TITLE
I can’t call the HD wallet function . T

### ISSUE THREAD

**Issue by wqmer** [ethereumjs/ethereumjs-wallet#34]
This code could work in server end . And I want to implement it on client end with html.
I have already applied the wallet and hd wallet browse build , still doesn't work. 

  <script type="text/javascript" src="./lib/jquery-3.3.1.min.js"></script>
  <script type="text/javascript" src="./lib/web3.min0_2.js"></script>
  <script type="text/javascript" src="./lib/bip39.min.js"></script>
  <script type="text/javascript" src="./lib/hdkey.min.js"></script>
  <script type="text/javascript" src="./lib/ethereumjs-wallet-hd-0.6.0.js"></script>
  <script type="text/javascript" src="./lib/ethereumjs-wallet-0.6.0.js"></script>

var mnemonic = seed_one ;
var hdwallet = hdkey.fromMasterSeed(bip39.mnemonicToSeed(mnemonic));
var wallet_hdpath = "m/44'/60'/0'/0/";
var wallets = {};
var addresses = [];
var num_addresses = 5 ;
var address_index = 0 ;
console.log(hdwallet);

// generate new addres by mnemonic
for (let i = address_index ; i < address_index  + num_addresses ; i++){
var wallet = hdwallet.derivePath(wallet_hdpath + i).getWallet();
var addr = '0x' + wallet.getAddress().toString('hex');
addresses.push(addr);
wallets[addr] = wallet;
    }

Uncaught TypeError: hdwallet.derivePath is not a function

**Comment by axic** [comment]
You are including the `hdkey` library and your `hdwallet` instance is not pointing to an instance of ethereumjs-wallet.
