### ISSUE TITLE
Add some practical code examples to README or a dedicated example file

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-wallet#35]

**Comment by junxion-io** [comment]
This should help. https://github.com/junxion-io/ethereumjs-wallet

**Comment by GeeeCoin** [comment]
@junxion-io can you provide some help with using the HD key submodule with wallet subpovider? https://github.com/ethereumjs/ethereumjs-wallet/issues/48 

I'll send a tip your way:)

**Comment by junxion-io** [comment]
What are you needing to do?

**Comment by junxion-io** [comment]
Sorry, I haven't used that aspect of the library yet. I would help if I could. So far I've only needed to load/parse keystore files and load in private keys.

**Comment by GeeeCoin** [comment]
Thanks for letting me know. Have you tested this library with web3 v1?

**Comment by junxion-io** [comment]
I haven't yet built web3 into my wallet app, but I will be soon. I mainly just needed to extract the public address from a keystore/private key. I'll be adding in more functionality soon. I will be more help in about a month :)

**Comment by GeeeCoin** [comment]
@junxion-io goodluck! There are simpler solutions for mashing your wallet with a public 'zero-client' node. I looked through the codebase of this truffle fork and seems safe: https://github.com/crypedit/truffle-wallet-provider
