### ISSUE TITLE
"npm install ethereumjs-wallet" 

### ISSUE THREAD

**Issue by Aaronzhou** [ethereumjs/ethereumjs-wallet#40]
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by holgerd77** [comment]
This is not a sufficient error description, will close.
