### ISSUE TITLE
crypto （This package has been deprecate）

### ISSUE THREAD

**Issue by echozhangzy8888** [ethereumjs/ethereumjs-wallet#41]
ERROR in ./node_modules/ethereumjs-wallet/index.js
    Module not found: Error: Can't resolve 'crypto' in '/Users/zheyi/work_energy/greenToken/weex/node_modules/ethereumjs-wallet'
     @ ./node_modules/ethereumjs-wallet/index.js 2:13-30
     @ ./node_modules/ethereumjs-wallet/hdkey.js

how can i solve

**Comment by xiaojay** [comment]
upgrade node to the lastest version, which included 'crypto' as build-in package。

**Comment by xiaojay** [comment]
do u want to make a eth wallet with weex on mobile phone?
yes, some build-in package can not resolve by  webpack.
check out this https://medium.com/@abrahamelmahrek/how-to-react-native-w-web3-0x-js-0xconnect-39b3d6a4dca; which package 'cypto' on react native.

I think same methods could work out in weex.
