### ISSUE TITLE
Help needed with using ethereumjs-util and ethereumjs-wallet for a js script

### ISSUE THREAD

**Issue by GreenAsGrass** [ethereumjs/ethereumjs-wallet#54]
Recently, a relative of mine, someone around 70 years of age and not very tech savvy, approached me to help him with his ethereum wallet. He was unable to access it and send some tokens. I soon realised that there was something wrong with his private key, as there were only 61 characters instead of 64. It was very unfortunate, as a lot of tokens were stuck in that wallet.

But I do believe that there is a way to bruteforce the private key out, since only 3 characters were missing. That was when I found a support article on missing characters of private key(linked below), as well as the javascript which was kindly shared with the public. 

https://support.mycrypto.com/private-keys-passwords/missing-characters-of-private-key.html
https://gist.github.com/tayvano/7755e3e8d8b64581d5ff2865087b93f8

However I believe there's some issue with the ethereumjs-util or wallet? I am not very experienced or tech savvy so I can't figure out what is wrong. But I have attached a screenshot as well

![1](https://user-images.githubusercontent.com/32706055/41862163-b2aaf7ea-78d5-11e8-9f90-fc73cd26d9ea.JPG)

**Comment by holgerd77** [comment]
Hi @GreenAsGrass, sorry, but as stories like this are generally not verifiable, we on-principle give no advice or help on brute force attacks or similar. I assume your story is correct and I wish you good look, but you will have to figure out yourself. The only thing I can say is that this seems very likely not having anything to do with the EthereumJS libraries, but with some basic stuff regarding Node installation or the like.

**Comment by holgerd77** [comment]
Sorry, I'll leave this as is for now.
