### ISSUE TITLE
Move from Travis to CircleCI

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-wallet#56]

**Comment by fanatid** [comment]
Out of interest, how CircleCI better then Travis?

**Comment by axic** [comment]
It uses docker images for each task (in Travis that needs to be done manually) and currently has much shorter queue times (e.g. much faster).

**Comment by holgerd77** [comment]
Superseded by https://github.com/ethereumjs/ethereumjs-wallet/pull/120, will close.
