### ISSUE TITLE
Rewrite in Typescript

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-wallet#58]

**Comment by holgerd77** [comment]
Does this needs to be rewritten or is working closer together with https://github.com/ethers-io/ethers.js and try to advocate an ``AssemblyScript`` compatible version an alternative?

**Comment by the-jackalope** [comment]
Are you looking for contributors on this issue? I'm experienced in Typescript rewrites of JS codebases and could probably knock this out in a day or two

**Comment by holgerd77** [comment]
@the-jackalope That would be great, yes, atm no one from the team has some capacity to do it! 😄

Can you formally follow closely some of the existing transition PRs, so regarding the re-use of TypeScript, format and linting configuration? Here is an example PR for some inspiration: https://github.com/ethereumjs/ethereumjs-util/pull/170/files

**Comment by the-jackalope** [comment]
Sounds good! I'll probably get round to it this weekend. Also thanks for the guide! Will peruse it and follow the guidelines.

Couple extra things - I see that the repo is using safe-buffer in lieu of Node's buffer types. This usually causes some difficulties in TypeScript where the compiler throws type errors when trying to use a safe-buffer where a NodeJS Buffer is needed instead. Am I good to replace safe-buffer with Node's Buffer or is there a reason to keep safe-buffer around?

**Comment by holgerd77** [comment]
No, we have decided to move safe-buffer from the libraries some time ago, go ahead and remove.
