### ISSUE TITLE
dist/hdkey.js (Maintainer Update: Critical bug in v0.6.1, now fixed with v0.6.2, please update!)

### ISSUE THREAD

**Issue by michaelsbradleyjr** [ethereumjs/ethereumjs-wallet#64]
With the new 0.6.1 release, this:

```
const hdkey = require('ethereumjs-wallet/hdkey');
```

Must be changed to:

```
const hdkey = require('ethereumjs-wallet/dist/hdkey');
```

Maybe that's not what you intended?  Even though your pkg.json main points at `dist/`, a module reference like `'ethereumjs-wallet/hdkey'` only works if `hdkey.js` is at the top-level of the package.

In the published package, you could include an `hdkey.js` that's a one-liner:

```
module.exports = require('./dist/hdkey.js');
```

However, you would need to reorg the sources that get transpiled by babel under `src/` and update the `build:dist` script accordingly.

**Comment by michaelsbradleyjr** [comment]
Here's how to reproduce the problem:

```
cd $(mktemp -d) \
&& npm init -y \
&& npm i ethereumjs-wallet@0.6.1 \
&& node -e "const hdkey = require('ethereumjs-wallet/hdkey');"
```

There will be an error reported in the console: `Error: Cannot find module 'ethereumjs-wallet/hdkey'`.

If `0.6.1` is changed to `0.6.0`, or if the module is specified as `'ethereumjs-wallet/dist/hdkey'` then it works.

**Comment by axic** [comment]
@holgerd77 can you have a look at this please?

**Comment by ianheCENNZ** [comment]
this is quite annoying, a upgrade of patch version shouldn't break anything which 0.6.1 breaks.

**Comment by nickjuntilla** [comment]
Switching the package file from "^0.6.0" to "^0.6.0" without the caret worked for me.

**Comment by sohkai** [comment]
@axic @holgerd77 If a fix will be longer than a few days, it might be better to republish `0.6.0` as `0.6.2`. This dependency breaking has been impacting a lot of packages.

**Comment by Dancia** [comment]
It's been not working for a while. Any fix soon?

**Comment by holgerd77** [comment]
Sorry, I'm somewhat on a leave and won't find the time to fix this in the next 1-2 weeks. Can some of you guys submit a PR on this?

**Comment by holgerd77** [comment]
(since this has already such a good error description, this should be a comprehensible amount of work to do)

**Comment by Mischi** [comment]
I think there is no easy solution to _restore_ the old import path (`'ethereumjs-wallet/hdkey'`) know that you transpile the src. 

Some projects publish only the contents of their `dist` directory by copying the package.json into the `dist` folder and doing an `npm publish` from within dist. This also has some disadvantages though - e.g. the original source will not be published.

I would suggest we follow @sohkai suggestion and just republish 0.6.0 as 0.6.2 and then republish 0.6.1 as 0.7.0. This at least should give dependent projects the chance to update explicitly.

**Comment by holgerd77** [comment]
Just googling on this, it's really impressive that there seems to be no way to set ``dist/`` as the new base/root directory in ``package.json``. Am I right on this or did I miss something? This would be a pretty easy solution.

**Comment by holgerd77** [comment]
Seems to be actively discussed, no help here though: https://github.com/nodejs/node/issues/21787

**Comment by holgerd77** [comment]
Ok, I now published this in the release above and tested the new release with the [test script](https://github.com/ethereumjs/ethereumjs-wallet/issues/64#issuecomment-408715971) from Michael above. This is now working.

Will leave this open for some confirmation that this works and generally some more days for reference.

**Comment by holgerd77** [comment]
Also deprecated the old ``v0.6.1`` release on npm.

**Comment by sohkai** [comment]
@holgerd77 Can confirm that this works, assuming no lock files have cached the 0.6.1 version.

**Comment by holgerd77** [comment]
@sohkai Great, thanks!
