### ISSUE TITLE
Unable to Generate Same Account from MetaMask Mnemonic

### ISSUE THREAD

**Issue by theomarshanti** [ethereumjs/ethereumjs-wallet#68]
Hello - 
I've been unable to generate the account I see in MetaMask from the same Mnemonic.
Due to the lack of documentation, I may be misunderstanding how to do so.
I have tried running the following in a Truffle Node console in my Terminal:

1)
`var seed = bip39.mnemonicToSeed(mnemonic)`
`var wallet_test = hdkey.fromMasterSeed(seed)`
`wallet_test.derivePath("m/44'/60'/0'/0/0")`
`wallet_test.derivePath("m/44'/60'/0'/0")`

2)
`var seed = bip39.mnemonicToSeedHex(mnemonic)`
`var wallet_test = hdkey.fromMasterSeed(seed)`
`wallet_test.derivePath("m/44'/60'/0'/0/0")`
`wallet_test.derivePath("m/44'/60'/0'/0")`

But none of them have outputted the same account I have in MetaMask. 
Can anyone point out why this doesn't work please?

If it helps, this does work with `truffle-hd-wallet-provider`

**Comment by Alexintosh** [comment]
Came here because of this.

**Comment by theomarshanti** [comment]
Thank you so much @Alexintosh - it worked

**Comment by witee-star** [comment]
https://cyberbump.net/metamask-ronin-and-binance-wallet-password-recovery-using-btcrecover-lost-or-forgotten-password/
