### ISSUE TITLE
Can not install package

### ISSUE THREAD

**Issue by gasparyanyur** [ethereumjs/ethereumjs-wallet#75]
I am trying to install package but getting an error look like this

> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\EvenPC\AppData\Local\Programs\Python\Python36\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:276:12)
> gyp ERR! stack     at emitTwo (events.js:126:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\Users\EvenPC\Even\chain\node_modules\scrypt
> gyp ERR! node -v v8.12.0
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the scrypt@6.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\EvenPC\AppData\Roaming\npm-cache\_logs\2018-10-29T13_12_57_933Z-debug.log

I have already installed `python`
```
C:\Users\EvenPC\Even\chain>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

How can I solve this error ?

**Comment by fanatid** [comment]
Probably 2.7 required
