### ISSUE TITLE
Wallet.getAddressString() returns all lower case string causing checksum to fail during signing

### ISSUE THREAD

**Issue by roschler** [ethereumjs/ethereumjs-wallet#76]
The `getAddressString()` method in the `Wallet` object returns the public address in all lower case.  This makes a subsequent call to the Web3JS `sign()` method fail because of a checksum capitalization check.  The `getAddressString()` method should return the address without changing the capitalization of it.

```
Provided address <address> is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
```

The other getters that return addresses as strings should do the same.

**Comment by axic** [comment]
There is a `getChecksumAddressString()` method returning the checksummed version.
