### ISSUE TITLE
Unable to transfer to ethereumjs-wallet address

### ISSUE THREAD

**Issue by rameshb444** [ethereumjs/ethereumjs-wallet#83]
Hi ,

I have generated private and public keys from ethereumjs-wallet.  
Also I have started my geth node private network and opened geth console. 

**Now I want to do transactions from accounts created using geth console address and ethereumjs-wallet address.**
It is showing error Invalid address below error. 

**Error: invalid address
    at web3.js:3930:15
    at web3.js:3759:22
    at web3.js:502 

Actually I want to create an exchange where users will have private and public keys. As I am unable to create private keys In geth,  I have used ethereumjs-wallet for private and public keys. Please let me know regarding this.

Thanks,
Ramesh.

**Comment by axic** [comment]
Can you show a larger log snippet?

**Comment by rameshb444** [comment]
Hi @axic,

Please find the attached files below,


**1st screenshot : I started my geth private network**

![screenshot from 2019-01-09 11-44-49](https://user-images.githubusercontent.com/19839852/50880376-3c8fea00-1404-11e9-99ec-28cda98fd5ed.png)


**2nd screenshot: I created private and public keys using ethereumjs-wallet address**

![screenshot from 2019-01-09 11-43-36](https://user-images.githubusercontent.com/19839852/50880441-677a3e00-1404-11e9-9892-96e26fdd4571.png)


**3rd screenshot : I am trying to send ethereum from accounts created using geth console address to ethereumjs-wallet address** 

![screenshot from 2019-01-09 11-43-46](https://user-images.githubusercontent.com/19839852/50880496-98f30980-1404-11e9-8970-f9c1919fa2a1.png)


Please let me know regarding this.


Thanks.

**Comment by rameshb444** [comment]
Hi @axic ,

This issue is fixed. Actually while sending transaction to address should be in double quotes. After changing that it worked fine.

Thanks.
