### ISSUE TITLE
Issue with creating Wallet from keystore

### ISSUE THREAD

**Issue by mzzovko** [ethereumjs/ethereumjs-wallet#84]
I'm trying to create Wallet object from keystore, and whenever I try to create it I get the following error:
```
Error: sorry, createDecipheriv is not implemented yet
we accept pull requests
```

Code that fails (it's run in browser):
`const accountObject = ethereumJsWallet.fromV3(keystore, password, true)`

Is it really not implemented, or am I using it wrong somehow?

**Comment by axic** [comment]
What system are you trying to run this on?

**Comment by mzzovko** [comment]
Hi axic, I'm running it in:
`Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)`
`Linux Mint 18.2`

Thing is, I'm not even sure how to debug this, or is it even a bug?
