### ISSUE TITLE
Private key security issue

### ISSUE THREAD

**Issue by chiro-hiro** [ethereumjs/ethereumjs-wallet#9]
After call `.fromV3()` or `.fromMasterSeed()` all **private key** will be decrypted/generated and store on memory, that's insecure. Could we store private key in encrypted form or defined a method to clear private key in memory?.

**Comment by axic** [comment]
I think this is a general problem with languages which don't offer strict memory management. There is no way to clear memory in Javascript as it is a garbage collected language.

**Comment by tad88dev** [comment]
I have tried to fill privKey Buffer with `myWallet.privKey.fill(0x0)`. I'm not sure that it's already clean.

**Comment by holgerd77** [comment]
No further discussion in close to 2 years, will close this.
