### ISSUE TITLE
Wallet's toV3 method does not match the official V3 keystore spec

### ISSUE THREAD

**Issue by the-jackalope** [ethereumjs/ethereumjs-wallet#94]
The official [V3 keystore spec](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) omits the `address` key from the outputted JSON, noting that it "compromises privacy".

The wallet's `toV3()` method includes an address key - we should remove it to conform to the official spec.

**Comment by axic** [comment]
I find this kind of funny given the filename contains the address. I think it make sense making it an option. What do you think?

**Comment by the-jackalope** [comment]
Sounds good to me! I'm not especially bothered by it, just thought I'd raise the issue since it's out of sync with the spec. Looks like it's not a point of contention for anyone.

I'll close this now.
