### ISSUE TITLE
Integrating with Chrome Extension

### ISSUE THREAD

**Issue by curldapps** [ethereumjs/ethereumjs-wallet#99]
I am working on putting together a chrome extension that requires the creation of single-use ethereum keys, and I wanted to see if ethereumjs-wallet is compatible with Chrome Extensions? I'd like to be able to create ethereum keys and sign a transaction message body within this extension without using MetaMask or the like. 

I don't necessarily need to be able to send the transaction to the mainnet directly, so I don't need a node or provider for web3.

Thanks!

**Comment by holgerd77** [comment]
Hi @curldapps, Chrome Extensions are written in JavaScript so I would suppose this should work, would be nice if you could post your experiences if you try to integrate here. Another option is to use the wallet from the [ethers.js](https://github.com/ethers-io/ethers.js) package. If you try both it would also be super-helpful if you give a short comparison of your experiences and some pitfalls here.
